#debug = true
defaultEntryPoints = ["https","http"]
insecureSkipVerify = true

[api]
entryPoint = "traefik"
dashboard = true

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]
    minVersion = "VersionTLS12"
    cipherSuites = [
      "TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305",
      "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384",
      "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256",
      "TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256",
      "TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA",
      "TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA"
    ]
  [entryPoints.traefik]
  address = ":8080"
  [entryPoints.traefik.auth.basic]
  # Basic auth for Traefik interface. This is admin/12345 - please change it.
  # Use htpasswd to generate yours, like this:
  #   docker run --rm -it httpd:alpine htpasswd -bnB admin 12345
  #users = ["admin:$2y$05$pHn0lBVoG1u8c8WDaS.AY.GE/B6BY6MC6yYBXM/sNL96N7A2CcrEW"]
  users = ["sicario:$2y$10$VVEVjU6bq56arCiiR5pDZOWiqNm9anqwpHEz25IK06h5NIbEaP9VW"]

[acme]
email = "info@fenyszaru.hu"
storage = "/etc/traefik/acme/acme.json"
entryPoint = "https"
onHostRule = true
onDemand = false
  [acme.httpChallenge]
  entryPoint = "http"

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "example.com"
watch = true
exposedbydefault = false
